--1
SELECT S.STUDENT_NO, S.STUDENT_NAME, S.ENTRANCE_DATE
FROM TB_STUDENT S
JOIN TB_CLASS C ON (C.DEPARTMENT_NO = S.DEPARTMENT_NO)
WHERE C.DEPARTMENT_NO = '002';

--2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3
SELECT PROFESSOR_NAME "교수이름", CASE
    WHEN TO_CHAR(SYSDATE, 'MMDD') >= SUBSTR(PROFESSOR_SSN, 3, 4) THEN TO_CHAR(SYSDATE, 'YY'
    ) + 100 - SUBSTR(PROFESSOR_SSN, 1, 2) + 1
    WHEN TO_CHAR(SYSDATE, 'DDMM') < SUBSTR(PROFESSOR_SSN, 3, 4)  THEN TO_CHAR(SYSDATE, 'YY'
    ) + 100 - SUBSTR(PROFESSOR_SSN, 1, 2)
                              END "나이"
FROM TB_PROFESSOR
ORDER BY 2;



--4
SELECT SUBSTR(PROFESSOR_NAME, 2, 2) "이름"
FROM TB_PROFESSOR;



--5
SELECT STUDENT_NO, STUDENT_NAME, FLOOR((ENTRANCE_DATE - TO_DATE(SUBSTR(STUDENT_SSN, 1, 6))
) / 365) + 1 "나이"
FROM TB_STUDENT
WHERE FLOOR((ENTRANCE_DATE - TO_DATE(SUBSTR(STUDENT_SSN, 1, 6))) / 365) < 19
ORDER BY STUDENT_NO;

--6
SELECT TO_CHAR(TO_DATE('20201225', 'YYYY-MM-DD'), 'DAY') "요일"
FROM DUAL;

--7
SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'), 'YYYY/MM/DD') "값1", TO_CHAR(TO_DATE('49/10/11'
, 'YY/MM/DD'), 'YYYY/MM/DD') "값2", TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY/MM/DD') "값3"
, TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY/MM/DD') "값4"
FROM DUAL;

--8
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(ENTRANCE_DATE, 1, 2) < 100 AND SUBSTR(ENTRANCE_DATE, 1, 2) > 23
ORDER BY STUDENT_NO DESC;

--9
SELECT TO_CHAR(AVG(POINT), 999.9)
FROM TB_GRADE
NATURAL JOIN TB_STUDENT
WHERE STUDENT_NO = 'A517178' AND STUDENT_NAME = '한아름';


--10
SELECT DISTINCT DEPARTMENT_NO "학과번호", COUNT(DEPARTMENT_NO) "학생수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;




--11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;



--12
SELECT SUBSTR(TERM_NO, 1, 4) "년도", ROUND(AVG(POINT), '1') "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY 1;

--13
SELECT DEPARTMENT_NO "학과코드명", SUM("ABSENCE_COUNT") "휴학생 수"
FROM(
SELECT DEPARTMENT_NO, COUNT(ABSENCE_YN) AS ABSENCE_COUNT
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
GROUP BY DEPARTMENT_NO
UNION
SELECT DEPARTMENT_NO, 0
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO)
GROUP BY DEPARTMENT_NO
ORDER BY 1;

--14
SELECT STUDENT_NAME "동일이름", COUNT(STUDENT_NAME) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1
ORDER BY 1;

SELECT *
FROM TB_STUDENT;

SELECT *
FROM TB_CLASS;

SELECT *
FROM TB_CLASS_PROFESSOR;

SELECT *
FROM TB_DEPARTMENT;

SELECT *
FROM TB_GRADE;
 
SELECT *
FROM TB_PROFESSOR;

--15
SELECT NVL(SUBSTR(TERM_NO, 1, 4), ' ') "년도", NVL(SUBSTR(TERM_NO, 5, 2), ' ') "학기", ROUND(AVG(POINT), '1') "평균"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO, 1, 4), SUBSTR(TERM_NO, 5, 2) )
ORDER BY SUBSTR(TERM_NO, 1, 4);