CREATE TABLE STUDYGROUP (
    GROUP_NO VARCHAR2(20) PRIMARY KEY, 
    ACADEMY VARCHAR2(20) NOT NULL, 
    GROUPNAME VARCHAR2(20) NOT NULL, 
    MEMBERCOUNT NUMBER NOT NULL, 
    WEIGHT NUMBER NOT NULL, 
    PENALTY NUMBER NOT NULL
);

SELECT *
FROM STUDYGROUP;