--1
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
ORDER BY 1;

--2
SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY 2 DESC;

--3
SELECT STUDENT_NAME, STUDENT_NO, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_NO LIKE '9%' AND ( STUDENT_ADDRESS LIKE '경기%' OR STUDENT_ADDRESS LIKE '강원%' )
ORDER BY 1;

--4
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = (
    SELECT DISTINCT D.DEPARTMENT_NO
    FROM TB_DEPARTMENT D
    JOIN TB_PROFESSOR P ON ( D.DEPARTMENT_NO = P.DEPARTMENT_NO )
    WHERE D.DEPARTMENT_NAME = '법학과'
)
ORDER BY PROFESSOR_SSN;

--5
SELECT STUDENT_NO, TO_CHAR(POINT, '999.99')
FROM TB_GRADE
WHERE TERM_NO = '200402' AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;

--6
SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
NATURAL JOIN TB_DEPARTMENT
ORDER BY STUDENT_NAME;

--7
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
NATURAL JOIN TB_DEPARTMENT
ORDER BY 2;

--8
SELECT C.CLASS_NAME, P.PROFESSOR_NAME
FROM TB_CLASS C
JOIN TB_PROFESSOR P ON ( C.DEPARTMENT_NO = P.DEPARTMENT_NO )
ORDER BY 2;

--9
SELECT STUDENT_NO "학번", STUDENT_NAME "학생 이름", TO_CHAR(AVG(POINT), '999.9') "전체 평점"
FROM TB_STUDENT
NATURAL JOIN TB_GRADE
GROUP BY STUDENT_NAME, STUDENT_NO;

--10
SELECT CLASS_NAME "학과이름", STUDENT_NAME "학생이름", PROFESSOR_NAME "지도교수이름"
FROM TB_STUDENT S
JOIN TB_CLASS C ON ( S.DEPARTMENT_NO = C.DEPARTMENT_NO )
JOIN TB_CLASS_PROFESSOR CP ON ( C.CLASS_NO = CP.CLASS_NO )
JOIN TB_PROFESSOR P ON ( CP.PROFESSOR_NO = P.PROFESSOR_NO );

--11
SELECT STUDENT_NAME, TERM_NO
FROM TB_STUDENT S
JOIN TB_GRADE G ON ( S.STUDENT_NO = G.STUDENT_NO )
JOIN TB_CLASS C ON ( G.CLASS_NO = C.CLASS_NO )
WHERE CLASS_NAME = '인간관계론' AND TERM_NO LIKE '2007%';

--12
SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON ( C.DEPARTMENT_NO = D.DEPARTMENT_NO )
WHERE D.CATEGORY = '예체능' AND C.CLASS_NO IN (
    SELECT CLASS_NO
    FROM TB_CLASS
    MINUS
    SELECT CLASS_NO
    FROM TB_CLASS_PROFESSOR
)
ORDER BY 2;

--13
SELECT S.STUDENT_NAME "학생이름", NVL(P.PROFESSOR_NAME, '지도교수 미지정') "지도교수"
FROM TB_STUDENT S
LEFT JOIN TB_PROFESSOR P ON (S.COACH_PROFESSOR_NO = P.PROFESSOR_NO)
JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '서반아어학과'
ORDER BY S.STUDENT_NO;


--14
SELECT G.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME, ROUND(AVG(G.POINT), 1)
FROM TB_GRADE G
JOIN TB_STUDENT S ON (S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
WHERE S.ABSENCE_YN = 'N'
GROUP BY G.STUDENT_NO, S.STUDENT_NAME, D.DEPARTMENT_NAME
HAVING ROUND(AVG(G.POINT), 1) >= '4.0'
ORDER BY G.STUDENT_NO;

--15
SELECT G.CLASS_NO, C.CLASS_NAME, ROUND(AVG(G.POINT), 1)
FROM TB_CLASS C
JOIN TB_DEPARTMENT D ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_GRADE G ON (C.CLASS_NO = G.CLASS_NO)
WHERE D.DEPARTMENT_NAME = '환경조경학과' AND C.CLASS_TYPE LIKE '전공%'
GROUP BY G.CLASS_NO, C.CLASS_NAME
ORDER BY G.CLASS_NO;

--16
SELECT STUDENT_NAME, STUDENT_ADDRESS
FROM TB_STUDENT
WHERE STUDENT_NAME !='최경희' AND ABSENCE_YN = 'N' AND DEPARTMENT_NO = (SELECT DEPARTMENT_NO
FROM TB_STUDENT
WHERE STUDENT_NAME = '최경희');

--17
SELECT STUDENT_NO, STUDENT_NAME
FROM (SELECT S.STUDENT_NO, S.STUDENT_NAME, ROUND(AVG(POINT),2)
FROM TB_STUDENT S
JOIN TB_GRADE G ON (S.STUDENT_NO = G.STUDENT_NO)
JOIN TB_DEPARTMENT D ON (D.DEPARTMENT_NO = S.DEPARTMENT_NO)
WHERE D.DEPARTMENT_NAME = '국어국문학과'
GROUP BY S.STUDENT_NO, S.STUDENT_NAME
ORDER BY 3 DESC)
WHERE ROWNUM < 2;

--18
SELECT D.DEPARTMENT_NAME "계열 학과명", ROUND(AVG(G.POINT),1)
FROM TB_DEPARTMENT D
JOIN TB_CLASS C ON (C.DEPARTMENT_NO = D.DEPARTMENT_NO)
JOIN TB_GRADE G ON (G.CLASS_NO = C.CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY
FROM TB_DEPARTMENT
WHERE DEPARTMENT_NAME = '환경조경학과')
GROUP BY DEPARTMENT_NAME
ORDER BY 1;


SELECT *
FROM TB_STUDENT;
SELECT *
FROM TB_CLASS;
SELECT *
FROM TB_CLASS_PROFESSOR;
SELECT *
FROM TB_DEPARTMENT;
SELECT *
FROM TB_GRADE;
SELECT *
FROM TB_PROFESSOR;