
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    ID VARCHAR(30),
    PASSWORD VARCHAR(30),
    NAME VARCHAR(50),
    ADDRESS VARCHAR(100),
    CONSTRAINT PK_ID PRIMARY KEY(ID)
);
INSERT INTO MEMBER(ID, PASSWORD, NAME, ADDRESS) VALUES('USER1', '1234', '구관원', '강남구');
SELECT * FROM MEMBER;
-----------------------------------------------
DROP TABLE MEMBER2;

CREATE TABLE MEMBER2(
    MEMBERID VARCHAR(100) PRIMARY KEY,
    MEMBERPASSWORD VARCHAR(150) NOT NULL,
    MEMBERNAME VARCHAR(50) NOT NULL,
    MEMBERADDRESS VARCHAR(200) NOT NULL
);

INSERT INTO MEMBER2(MEMBERID, MEMBERPASSWORD, MEMBERNAME, MEMBERADDRESS)
SELECT ID, PASSWORD, NAME, ADDRESS FROM MEMBER_DTO;

COMMIT;



DROP TABLE MEMBER_DTO;
CREATE TABLE MEMBER_DTO(
    ID VARCHAR(30),
    PASSWORD VARCHAR(30),
    NAME VARCHAR(50),
    ADDRESS VARCHAR(100)
--    CONSTRAINT PK_ID PRIMARY KEY(ID)
);
INSERT INTO MEMBER_DTO(ID, PASSWORD, NAME, ADDRESS) VALUES('USER1', '1234', '김유저', '경기도');
UPDATE MEMBER_DTO SET ID = 'user1' WHERE NAME ='dfwdc';
UPDATE MEMBER_DTO SET PASSWORD = '1111', NAME = '길동이', ADDRESS = '전라도' WHERE ID = 'asdfas';
COMMIT;
SELECT * FROM MEMBER_DTO;
---------------------------------------------------
DROP TABLE ITEM;

CREATE TABLE ITEM(
    ITEM_ID NUMBER PRIMARY KEY,
    ITEM_NAME VARCHAR2(45),
    PRICE NUMBER,
    DESCRIPTION VARCHAR2(100),
    PICTURE_URL VARCHAR2(45),
    COUNT NUMBER
);
CREATE SEQUENCE SEQ_ITEM;
INSERT INTO ITEM VALUES(SEQ_ITEM.NEXTVAL, '딸기', 4500, '면역력을 강화시켜 질병에 효과적이다.', 'img/berry.jpg', 0);
INSERT INTO ITEM VALUES(SEQ_ITEM.NEXTVAL, '포도', 5000, '철분이 많고 빈혈을 예방한다.', 'img/grape.jpg', 0);
INSERT INTO ITEM VALUES(SEQ_ITEM.NEXTVAL, '귤', 4000, '눈 건강 살리고 피로 회복, 혈압 안정시키는 비타민 A가 많다.', 'img/gual.jpg', 0);
INSERT INTO ITEM VALUES(SEQ_ITEM.NEXTVAL, '키위', 8000, '키위 1개에 함유된 비타민 C는 오렌지의 2배, 비타민 E는 사과의 6배나 된다.', 'img/kiwi.jpg', 0);
INSERT INTO ITEM VALUES(SEQ_ITEM.NEXTVAL, '레몬', 3000, '구연산 비타민C가 풍부하여 피로회복에 도움이 된다.', 'img/lemon.jpg', 0);
COMMIT;
SELECT * FROM ITEM;

SELECT * FROM ITEM WHERE ITEM_ID = 1;

------------------------------------------------------------------------
DROP TABLE MEMBER_07;

CREATE TABLE MEMBER_07(
    NAME VARCHAR(100) PRIMARY KEY,
    AGE VARCHAR(150) NOT NULL,
    ADDR VARCHAR(200) NOT NULL
);

COMMIT;

-----------------------------------------------------------------------------

DROP TABLE TB_USER;

CREATE TABLE TB_USER(

USER_NO NUMBER PRIMARY KEY,

USER_ID VARCHAR2(50) UNIQUE NOT NULL,

USER_NAME VARCHAR2(50) NOT NULL,

USER_AGE NUMBER NOT NULL

);

CREATE SEQUENCE SEQ_UNO

START WITH 1

INCREMENT BY 1

NOCACHE;



-- 샘플 데이터 삽입

INSERT INTO TB_USER VALUES(SEQ_UNO.NEXTVAL, 'gd_hong', '홍길동', 20);

INSERT INTO TB_USER VALUES(SEQ_UNO.NEXTVAL, 'sh_han', '한소희', 28);

INSERT INTO TB_USER VALUES(SEQ_UNO.NEXTVAL, 'jm_park', '지민', 27);

COMMIT;


------------------------------------------------

DROP TABLE student;

CREATE TABLE student(

student_number NUMBER PRIMARY KEY,

student_name VARCHAR2(40) NOT NULL,

korean_score NUMBER NOT NULL,

english_score NUMBER NOT NULL,

math_score NUMBER NOT NULL

);

DROP TABLE manager;

CREATE TABLE manager(

manager_number NUMBER PRIMARY KEY,

manager_name VARCHAR2(40) NOT NULL,

manager_hire_date Date NOT NULL

);


INSERT INTO manager VALUES(SEQ_UNO.NEXTVAL, '가나다라마', '2222-01-01');
COMMIT;


--------------------------------------------
DROP TABLE MEMBER;

CREATE TABLE MEMBER(

USER_NO NUMBER PRIMARY KEY,

USER_ID VARCHAR2(20) NOT NULL,

USER_PW VARCHAR2(20) NOT NULL,

USER_NAME VARCHAR2(20) NOT NULL,

USER_ADDR VARCHAR(50) NOT NULL,

REG_DATE DATE DEFAULT SYSDATE

);

CREATE SEQUENCE SEQ_MEMBER;