--1
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, ROWNUM "순위"
FROM(
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, (E.SALARY + E.SALARY* NVL(E.BONUS, '0'))*12
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (D.DEPT_ID = E.DEPT_CODE)
JOIN JOB J ON (J.JOB_CODE = E.JOB_CODE)
ORDER BY (E.SALARY + E.SALARY* NVL(E.BONUS, '0'))*12 DESC)
WHERE ROWNUM < 6;

--2
SELECT D.DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE E
JOIN DEPARTMENT D ON (D.DEPT_ID = E.DEPT_CODE)
GROUP BY E.DEPT_CODE, D.DEPT_TITLE
HAVING SUM(SALARY) > 0.2 * (SELECT SUM(SALARY)
FROM EMPLOYEE E); 

--3
WITH A AS (SELECT SUM(SALARY) "SUM(SALARY)", AVG(SALARY) "AVG(SALARY)"
FROM EMPLOYEE)

SELECT "SUM(SALARY)" , "AVG(SALARY)"
FROM A;