--1
SELECT 
STUDENT_NO, STUDENT_NAME, ENTRANCE_DATE
FROM TB_STUDENT
NATURAL JOIN TB_CLASS
WHERE DEPARTMENT_NO = '002';

--2
SELECT
PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3
SELECT
PROFESSOR_NAME "교수이름",
CASE
WHEN TO_CHAR(SYSDATE, 'MMDD') >= SUBSTR(PROFESSOR_SSN, 3, 4)
THEN TO_CHAR(SYSDATE, 'YY')+100 - SUBSTR(PROFESSOR_SSN, 1, 2)  + 1
WHEN TO_CHAR(SYSDATE, 'DDMM') < SUBSTR(PROFESSOR_SSN, 3, 4)
THEN TO_CHAR(SYSDATE, 'YY')+100 - SUBSTR(PROFESSOR_SSN, 1, 2)
END "나이"
FROM TB_PROFESSOR
ORDER BY 2;

--4
SELECT SUBSTR(PROFESSOR_NAME,2,2) "이름"
FROM TB_PROFESSOR;

--5
SELECT
STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - (SUBSTR(STUDENT_SSN, 1 ,2)+1900) < 20;

--6
SELECT
TO_CHAR(TO_DATE('20201225', 'YYYY-MM-DD'), 'DY')
FROM DUAL;

--7
SELECT
TO_DATE('99/10/11', 'YY/MM/DD'), TO_DATE('49/10/11', 'YY/MM/DD'),
TO_DATE('99/10/11', 'RR/MM/DD'), TO_DATE('49/10/11', 'RR/MM/DD')
FROM DUAL;

--8
SELECT
STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(ENTRANCE_DATE,1,2) < 100 AND SUBSTR(ENTRANCE_DATE,1,2) > 23
ORDER BY STUDENT_NO DESC;

--9
SELECT
TO_CHAR(AVG(POINT), 999.9)
FROM TB_GRADE
NATURAL JOIN TB_STUDENT
WHERE STUDENT_NO = 'A517178' AND STUDENT_NAME = '한아름';


--10
SELECT
DISTINCT DEPARTMENT_NO "학과번호", COUNT(DISTINCT DEPARTMENT_NO
FROM TB_DEPARTMENT
NATURAL JOIN TB_STUDENT
ORDER BY 1;